;设置规则标志位
ruleset=DIRECT,https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list
ruleset=DIRECT,https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/Download/Download.list

ruleset=Domestic,https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/HoYoverse/HoYoverse.list

ruleset=Apple,https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list

ruleset=CMedia,https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.list
ruleset=CMedia,https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/Himalaya/Himalaya.list
ruleset=CMedia,https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/iQIYI/iQIYI.list
ruleset=CMedia,https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/KugouKuwo/KugouKuwo.list
ruleset=CMedia,https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/NetEaseMusic/NetEaseMusic.list
ruleset=CMedia,https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/TencentVideo/TencentVideo.list
ruleset=CMedia,https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/Youku/Youku.list
ruleset=CMedia,https://raw.gitmirror.com/iseemecan/Clash/master/Ruleset/CMedia.list

ruleset=Google,https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list
ruleset=Google,https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list

ruleset=GMedia,https://raw.gitmirror.com/iseemecan/Clash/master/Ruleset/GMedia.list
ruleset=GMedia,https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/AbemaTV/AbemaTV.list
ruleset=GMedia,https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.list
ruleset=GMedia,https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/BBC/BBC.list
ruleset=GMedia,https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBO/HBO.list
ruleset=GMedia,https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/Hulu/Hulu.list

ruleset=Disney,https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list
ruleset=Netflix,https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list
ruleset=Spotify,https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list

ruleset=Telegram,https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=PayPal,https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/PayPal/PayPal.list
ruleset=GitHub,https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list
ruleset=Microsoft,https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list
ruleset=Speedtest,https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list
ruleset=Steam,https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.list

ruleset=Proxies,https://raw.gitmirror.com/iseemecan/Clash/master/Ruleset/Proxy.list
ruleset=Proxies,https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/ProxyLite/ProxyLite.list
ruleset=Domestic,https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/Tencent/Tencent.list
ruleset=Domestic,https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.list
ruleset=Domestic,[]GEOIP,CN
ruleset=Others,[]MATCH
;设置规则标志位

;设置分组标志位
custom_proxy_group=Proxies`select`[]香港`[]日本`[]手动选择
custom_proxy_group=Others`select`[]Proxies`[]DIRECT
custom_proxy_group=Apple`select`[]DIRECT`[]Proxies
custom_proxy_group=CMedia`select`[]DIRECT`[]Proxies
custom_proxy_group=Domestic`select`[]DIRECT`[]Proxies
custom_proxy_group=GMedia`select`[]香港`[]美国`[]手动选择
custom_proxy_group=Google`select`[]香港`[]日本`[]手动选择
custom_proxy_group=Github`select`[]香港`[]日本`[]手动选择
custom_proxy_group=Telegram`select`[]香港`[]日本`[]手动选择
custom_proxy_group=Disney`select`[]香港`[]新加坡`[]手动选择
custom_proxy_group=Netflix`select`[]香港`[]新加坡`[]手动选择
custom_proxy_group=Steam`select`[]DIRECT`[]Proxies
custom_proxy_group=PayPal`select`[]DIRECT`[]Proxies
custom_proxy_group=Spotify`select`[]DIRECT`[]Proxies
custom_proxy_group=Speedtest`select`[]DIRECT`[]Proxies
custom_proxy_group=Microsoft`select`[]Proxies`[]DIRECT
custom_proxy_group=专线`select`^((?!台|新|韩|美).)*专线((?!台|新|韩|美).)*$
custom_proxy_group=Auto-URL`url-test`^((?!专线).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=手动选择`select`[]专线`[]香港`[]台湾`[]日本`[]韩国`[]美国`[]新加坡`[]Auto-URL`^((?!专线).)*$
custom_proxy_group=日本`url-test`^((?!专线).)*(日|JP|Japan)((?!专线).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=台湾`url-test`^((?!专线).)*(台|TW|Taiwan)((?!专线).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=香港`url-test`^((?!专线).)*(港|HK|Hong Kong)((?!专线).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=韩国`url-test`^((?!专线).)*(韩|KR|首尔|Korea)((?!专线).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=美国`url-test`^((?!专线).)*(美|US|United States)((?!专线).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=新加坡`url-test`^((?!专线).)*(新|SG|狮城|Singapore)((?!专线).)*$`http://www.gstatic.com/generate_204`300,,50
;设置分组标志位
